MAJORITY ELEMENT

In [ ]:
def majority_element(lst):
  visited=[]
  m=len(lst)
  for i in range(len(lst)):
    if lst[i] not in visited:
      count=0
      for j in range(len(lst)):
        if lst[i]==lst[j]:
          count+=1
  if count==m/2:
    print(lst[i])
  else:
    print("not found")
majority_element([12,34,12,23,23,12])



12


SPIRAL ORDER

In [ ]:
def spiralOrder(matrix):
    if not matrix:
        return []

    top, bottom = 0, len(matrix) - 1
    left, right = 0, len(matrix[0]) - 1

    result = []
    while top <= bottom and left <= right:
        for i in range(left, right + 1):
            result.append(matrix[top][i])
        top += 1
        for i in range(top, bottom + 1):
            result.append(matrix[i][right])
        right -= 1
        if top <= bottom:
            for i in range(right, left - 1, -1):
                result.append(matrix[bottom][i])
            bottom -= 1
        if left <= right:
            for i in range(bottom, top - 1, -1):
                result.append(matrix[i][left])
            left += 1

    return result
matrix = [
    [1, 2, 3],
    [4, 5, 6],
    [7, 8, 9],
    [10,11,12]
]

print(spiralOrder(matrix))

[1, 2, 3, 6, 9, 12, 11, 10, 7, 4, 5, 8]


MATRIX OPERATION

In [ ]:
import numpy as np
a=np.matrix([[1,2],[3,4]])
b=np.matrix([[1,4],[5,6]])
print("addition of two matrix")
print(a+b)
print("subtraction of two matrix")
print(a-b)
print("product of two matrix")
print(a*b)

addition of two matrix
[[ 2  6]
 [ 8 10]]
subtraction of two matrix
[[ 0 -2]
 [-2 -2]]
product of two matrix
[[11 16]
 [23 36]]


LARGEST CONSECUTIVE SEQUENCE

In [ ]:
a=[1,2,3,5,100,200]
longest=0
for num in a:
  if num-1 not in a:
    current=num
    length=1
    while current+1 in a:
      current+=1
      length+=1
    longest=max(longest,length)
print(longest)

3


REMOVE DUPLICATES

In [ ]:
n=[10,20,18,14,20,10]
m=set(n)
print(m)

{10, 18, 20, 14}


ROTATION


In [ ]:
n=[10,20,30,40,50]
k=2
n1=[0]*len(n)
l=len(n)
for i in range(l):
  if i+k>=1:
    n1[i+k-l]=n[i]
print(n1)

[40, 50, 10, 20, 30]


PAIR OF NUMBERS

In [ ]:
def pair(lst):
  m=4
  for i in range(len(lst)):
    for j in range(len(lst)):
      if lst[i]+lst[j] == m:
        print(lst[i],lst[j])
pair([1,4,2,5,0])

4 0
2 2
0 4


In [ ]:
a=[1,2,3,2,1,4]
b=set(a)
print(b)

{1, 2, 3, 4}


FREQUENCY

In [ ]:
def frequency(lst):
  visited=[]
  for i in range(len(lst)):
    if lst[i] not in visited:
      count=0
      for j in range(len(lst)):
        if lst[i]==lst[j]:
          count+=1
    print(lst[i],count)
frequency([12,34,12,23])




12 2
34 1
12 2
23 1


LARGEST SECOND NUMBER

In [ ]:
def largest(m):
  m=list(set(m))
  print(m)
  n=sorted(m)
  print(n)
  print(n[-2])
largest(m)


[1, 2, 3, 4, 5]
[1, 2, 3, 4, 5]
4


In [ ]:
m=[2,3,1,4,5]

In [ ]:
a=[12,45,23,45,67,12]
m=list(set(a))
print(m)
for i in range(len(m)-1):
  if m[i]<m[i+1]:
    temp=m[i]
    m[i]=m[i+1]
    m[i+1]=temp
print(m)
print(m[1])

[67, 12, 45, 23]
[67, 45, 23, 12]
45
