In [1]:
import numpy as np
# 1a. Create a 4x4 identity matrix and print it.
# 1b. Create a 3x3 matrix filled with the number 7 (hint: np.full).
# 1c. Create a vector of 10 evenly spaced numbers between 0 and 1
#     (hint: np.linspace).
#
# --- your code here ---
print("marices and vector\n")
print("1a.")
def matrix_4():
  m=np.eye(4)
  print("4 x4 identity matrix:",m)
matrix_4()

print("1b.")
def full_matrix():
  n=np.full((3,3),7)
  print("3 x3 matrix filled with the number 7:",n)
full_matrix()

print("1c.")
def evenly_spread():
  p=np.linspace(1,10,num=6,dtype=float)
  print(" vector of 10 evenly spaced numbers between 0 and 1:",p)
evenly_spread()
print()

# ---------------------------------------------------------------
# 2. Matrix Multiplication
# ---------------------------------------------------------------

# 2a. Given A = [[2, 0], [0, 2]] and B = [[1, 2], [3, 4]], compute A@B
#     by hand, then verify with NumPy.
# 2b. Multiply a 3x2 matrix by a 2x4 matrix. What shape is the result?
# 2c. Explain (in a comment) why A*B and A@B give different results.
#
# --- your code here ---
print("matrix multiplication\n")
print("2a.")
A=np.array([[2,0],[0,2]])
B=np.array([[1,2],[3,4]])
print("matrix multiplication:",A@B)
print("2b.")
A=np.array([[1,2],[3,4],[4,5]])
B=np.array([[1,2,3,4],[5,6,7,8]])
c=A@B
print("shape of the result A@B:",np.shape(c))
print("2c.")
print(" A * B performs element-wise multiplication, multiplying corresponding elements of A and B")
print(" A @ B performs matrix multiplication, where rows of A are multiplied by columns of B according")
print(" to the rules of linear algebra. Therefore, A * B and A @ B generally produce different results.")
print()

# ---------------------------------------------------------------
# 3. Transpose
# ---------------------------------------------------------------

# 3a. Create a 3x5 matrix and confirm its transpose has shape (5, 3).
# 3b. Verify that (A @ B).T equals B.T @ A.T for two matrices A, B.
#
# --- your code here ---
print("Transpose\n")
print("3a.")
E=np.array([[1,2,3,4,5],[6,7,8,9,10],[11,12,13,14,15]])
c=np.transpose(E)
print("shape of transpose B is:",np.shape(c))
print("3b.")
import numpy as np

A = np.array([[1, 2, 3],
              [4, 5, 6]])

B = np.array([[7, 8],
              [9, 10],
              [11, 12]])

left = (A @ B).T
right = B.T @ A.T

print("(A @ B).T:\n", left)
print("\nB.T @ A.T:\n", right)
print("\nAre they equal?", np.allclose(left, right))
print()

# ---------------------------------------------------------------
# 4. Determinant
# ---------------------------------------------------------------

# 4a. Compute the determinant of a 3x3 matrix of your choice.
# 4b. Create a singular (non-invertible) matrix and show its
#     determinant is (approximately) zero.
#
# --- your code here ---
print("determinant\n")
print("4a.")
def det_matrix():
  A = np.array([[4,1, 2], [7,5,6],[3,4,5]])
  det = np.linalg.det(A)
  print("Determinant of A:", det)
det_matrix()
print("4b.")
def singluar():
  m=np.array([[1,2,3],[2,4,6],[3,6,9]])
  det = np.linalg.det(m)
  print("Determinant of m:", det)
singluar()
print()
# ---------------------------------------------------------------
# 5. Matrix Inverse
# ---------------------------------------------------------------

# 5a. Try to invert a singular matrix and observe the error NumPy
#     raises (hint: wrap in try/except).
# 5b. Verify that (A_inv)_inv == A for a matrix of your choice.
#
# --- your code here ---
print("matrix inverse\n")

print("5a.")
A = np.array([[1, 2],
              [2, 4]])

print("Matrix A:\n", A)

try:
    A_inv = np.linalg.inv(A)
    print("Inverse:\n", A_inv)
except np.linalg.LinAlgError as e:
    print("Error:", e)

print("5b.")

def INV_matrix():
  A = np.array([[1,2],[4,5]])
  print("the matrix A:",A)
  inverse = np.linalg.inv(A)
  inverse_inverse=np.linalg.inv(inverse)
  print("inverse of A:", inverse_inverse)

INV_matrix()
print()



# ---------------------------------------------------------------
# 6. Solving Systems of Linear Equations
# ---------------------------------------------------------------

# 6a. Solve the system:
#       x + y + z = 6
#       2y + 5z = -4
#       2x + 5y - z = 27
# 6b. Compare np.linalg.solve(A, b) with computing
#     np.linalg.inv(A) @ b. Which is generally preferred, and why?
#
# --- your code here ---
print("solving systems of linear equations\n")
print("6a.")
def solve():
  a=np.array([[1,1,1],[0,2,5],[2,5,-1]])
  b=np.array([6,-4,27])
  x = np.linalg.solve(a, b)
  y=np.linalg.inv(a) @ b
  print("the solutions of the system are x,y,z respectively",x)
  print("it is solved by formula np.linalg.inv(A) @ b:",y)
solve()

print("6b.")
print("both give the same answer first method is prefer as it gives fast response")
print()



# ---------------------------------------------------------------
# 7. Eigenvalues and Eigenvectors
# ---------------------------------------------------------------

# 7a. Verify A @ v == lambda * v for each eigenvalue/eigenvector pair.
# 7b. Find the eigenvalues of a diagonal matrix and explain the
#     pattern you notice.
#
# --- your code here ---
print("eigenvalues and eigenvectors\n")
print("7a.")
A = np.array([[4, 2],
              [1, 3]])
eigenvalues, eigenvectors = np.linalg.eig(A)

print("Eigenvalues:", eigenvalues)
print("Eigenvectors:\n", eigenvectors)

for i in range(len(eigenvalues)):
    lam = eigenvalues[i]
    v = eigenvectors[:, i]

    Av = A @ v
    lv = lam * v
    print("A @ v =", Av)
    print("λ * v =", lv)
    print("Verification:", np.allclose(Av, lv))
print("7b.")

D = np.array([[5, 0, 0],
              [0, 2, 0],
              [0, 0, 7]])

eigenvalues, eigenvectors = np.linalg.eig(D)

print("Diagonal Matrix:\n", D)
print("Eigenvalues:", eigenvalues)
print("Eigenvectors:\n", eigenvectors)
print("for diagonal matrix the diagonal elements are itself eigen values")
print()

# ---------------------------------------------------------------
# 8. Norms (vector and matrix length/magnitude)
# ---------------------------------------------------------------

# 8a. Compute the L2 norm of a 5-dimensional vector.
# 8b. Normalize a vector (divide by its own norm) so its length is 1,
#     and verify the result with np.linalg.norm.
#
# --- your code here ---
print("norms\n")
print("8a.")
v=np.array([1,2,3,4,5])
l1=np.linalg.norm(v)
print("norm of a 5-dimensional vector:" ,l1)
print("8b.")

unit_v=v/np.linalg.norm(v)
print("normalized vector:",unit_v)
l2=np.linalg.norm(unit_v)
print("norms of normalized vector",l2)
print()



# ---------------------------------------------------------------
# 9. Rank of a Matrix
# ---------------------------------------------------------------

# 9a. Construct a 4x4 matrix with rank 2.
# 9b. Explain (in a comment) the relationship between rank and
#     whether a matrix is invertible.
#
# --- your code here ---
print("rank of matrix\n")

print("9a.")
def example_rank():


    full_rank = np.array([[1, 2,3,4], [5,6,7,8],[9,10,11,12],[13,14,15,16]])


    print("Full-rank matrix:\n", full_rank, "-> rank =", np.linalg.matrix_rank(full_rank))
example_rank()
print("9b.")
print("A square matrix is invertible only if it has full rank (rank == n). where n is n x n matrix")
print()

# ---------------------------------------------------------------
# 10. Singular Value Decomposition (SVD)
# ---------------------------------------------------------------

# 10a. Reconstruct A from its SVD components and confirm it matches
#      the original (use np.allclose).
# 10b. Use SVD to compute a low-rank approximation of A by keeping
#      only the largest singular value. How close is it to A?
#
# --- your code here ---
print("singulae value decompostion\n")
def example_svd():
    print("10a.")
    A = np.array([[1, 2], [3, 4], [5, 6]])
    U, S, Vt = np.linalg.svd(A)

    print("A:\n", A)
    print("U:\n", U)
    print("Singular values S:", S)
    print("V^T:\n", Vt)


    S_full = np.zeros(A.shape)
    np.fill_diagonal(S_full, S)
    A_reconstructed = U @ S_full @ Vt
    print("Reconstructed A:\n", A_reconstructed)
    print("original A",np.allclose(A,A_reconstructed))
    print()

    print("10.b")
    S_rank1 = np.zeros_like(S_full)
    S_rank1[0, 0] = S[0]

    A_rank1 = U @ S_rank1 @ Vt

    print("\nRank-1 Approximation:")
    print(A_rank1)

    print("\nIs it equal to A?")
    print(np.allclose(A, A_rank1))

    # Measure approximation error
    error = np.linalg.norm(A - A_rank1)
    print("Frobenius norm of error:", error)
example_svd()



marices and vector

1a.
4 x4 identity matrix: [[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]
1b.
3 x3 matrix filled with the number 7: [[7 7 7]
 [7 7 7]
 [7 7 7]]
1c.
 vector of 10 evenly spaced numbers between 0 and 1: [ 1.   2.8  4.6  6.4  8.2 10. ]

matrix multiplication

2a.
matrix multiplication: [[2 4]
 [6 8]]
2b.
shape of the result A@B: (3, 4)
2c.
 A * B performs element-wise multiplication, multiplying corresponding elements of A and B
 A @ B performs matrix multiplication, where rows of A are multiplied by columns of B according
 to the rules of linear algebra. Therefore, A * B and A @ B generally produce different results.

Transpose

3a.
shape of transpose B is: (5, 3)
3b.
(A @ B).T:
 [[ 58 139]
 [ 64 154]]

B.T @ A.T:
 [[ 58 139]
 [ 64 154]]

Are they equal? True

determinant

4a.
Determinant of A: 13.0
4b.
Determinant of m: 0.0

matrix inverse

5a.
Matrix A:
 [[1 2]
 [2 4]]
Error: Singular matrix
5b.
the matrix A: [[1 2]
 [4 5]]
inverse of A: [[1. 2.]
 [4. 5